package net.runelite.client.plugins.bloodrunecrafter;

public enum bloodrunecrafterState
{
	ANIMATING,
	DROP_EXCEPT,
	FIND_GAME_OBJECT,
	ITERATING,
	MISSING_ITEMS,
	MOVING,
	TIMEOUT,
	WAIT_DENSE_ESSENCE,
	BLOOD_OBSTACLE_1,
	BLOOD_OBSTACLE_2,
	CLICK_DARK_ALTAR,
	CLICK_BLOOD_ALTAR,
	CHISEL_AT_ALTAR,
	CHISEL_WHILE_RUNNING,
	WALK_BLOOD_ALTAR,
	WALK_TO_ESSENCE;
}
